name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - "supabase/functions/**"
      - ".github/workflows/deploy-edge-functions.yml"
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref utwhvnafvtardndgkbjn

      - name: Deploy all Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy --project-ref utwhvnafvtardndgkbjn --all
